apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accessapplications.strive.io
spec:
  group: strive.io
  names:
    kind: AccessApplication
    listKind: AccessApplicationList
    plural: accessapplications
    singular: accessapplication
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              status:
                enum:
                - Uninitialized
                - Done
                type: string
              applicationId:
                type: string
            type: object
          spec:
            properties:
              name:
                type: string
              domains:
                items:
                  type: string
                type: array
              accountId:
                type: string
              apiToken:
                properties:
                  name:
                    type: string
                  key:
                    type: string
                  namespace:
                    nullable: true
                    type: string
                required:
                - name
                - key
                type: object
              accessPolicies:
                items:
                  type: string
                type: array
              visibleInLauncher:
                type: boolean
              logoUrl:
                nullable: true
                type: string
            required:
            - name
            - domains
            - accountId
            - apiToken
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}