namespace: cloudflared-operator-system
namePrefix: cloudflared-operator-
commonLabels:
  operator: cloudflared-operator
resources:
- operator-role.yaml
- operator-role-binding.yaml
- deployment.yaml
- service.yaml
- validators.yaml
- accessapplications_strive_io.yaml
- tunnels_strive_io.yaml
- tunnelaccesss_strive_io.yaml
- namespace.yaml
images:
- name: operator
  newName: ghcr.io/${{ env.IMAGE_NAME }}:${{ needs.release-please.outputs.tag_name }}
  newTag: latest
configMapGenerator:
- name: webhook-config
  literals:
  - KESTREL__ENDPOINTS__HTTP__URL=http://0.0.0.0:5000
  - KESTREL__ENDPOINTS__HTTPS__URL=https://0.0.0.0:5001
  - KESTREL__ENDPOINTS__HTTPS__CERTIFICATE__PATH=/certs/svc.pem
  - KESTREL__ENDPOINTS__HTTPS__CERTIFICATE__KEYPATH=/certs/svc-key.pem
secretGenerator:
- name: webhook-ca
  files:
  - ca.pem
  - ca-key.pem
- name: webhook-cert
  files:
  - svc.pem
  - svc-key.pem
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization