apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tunnelaccesss.strive.io
spec:
  group: strive.io
  names:
    kind: TunnelAccess
    listKind: TunnelAccessList
    plural: tunnelaccesss
    singular: tunnelaccess
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              targets:
                items:
                  properties:
                    name:
                      type: string
                    host:
                      type: string
                    port:
                      format: int32
                      type: integer
                  required:
                  - name
                  - host
                  - port
                  type: object
                type: array
              accessTokenRef:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                  optional:
                    nullable: true
                    type: boolean
                type: object
              secretAccessTokenRef:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                  optional:
                    nullable: true
                    type: boolean
                type: object
            required:
            - accessTokenRef
            - secretAccessTokenRef
            type: object
        type: object
    served: true
    storage: true