apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tunnels.strive.io
spec:
  group: strive.io
  names:
    kind: Tunnel
    listKind: TunnelList
    plural: tunnels
    singular: tunnel
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              status:
                enum:
                - Uninitialized
                - Created
                - Deploying
                - Done
                - MissingDns
                - MissingTunnel
                type: string
              messages:
                items:
                  type: string
                type: array
              tunnelId:
                type: string
            type: object
          spec:
            properties:
              name:
                description: Name of the tunnel
                type: string
              accountId:
                type: string
              apiToken:
                properties:
                  name:
                    type: string
                  key:
                    type: string
                  namespace:
                    nullable: true
                    type: string
                required:
                - name
                - key
                type: object
              resourceNamespace:
                type: string
              dns:
                items:
                  properties:
                    hostname:
                      type: string
                    path:
                      nullable: true
                      type: string
                    service:
                      type: string
                  required:
                  - hostname
                  - service
                  type: object
                type: array
            required:
            - name
            - accountId
            - apiToken
            - resourceNamespace
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}